---
swagger: "2.0"
info:
  description: "Documentación de los servicios Multiva Sprint 1  <a href='https://drive.google.com/open?id=0B_OaZlYG0i2ndHJUT3VFem5LWlk'>Documento Compartido</a>" 
  version: "0.1.0"
  title: "Grupo Financiero Multiva"
host: "200.39.24.141"
basePath: "/BEO"
tags:
- name: "Core Bancario"
  description: "Primer Login (Dinámico  y Estático)"
  externalDocs:
    description: "Primer Login"
    url: "http://200.39.24.141:9090/docs"
paths:
  /consultaDatosCliente:
    post:
      tags:
      - "ESB Fuse"
      description: "Realiza la consulta de los datos del cliente"
      parameters:
      - in: "body"
        name: "/consultaDatosClientes"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/consultaDatosCliente-in"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/consultaDatosCliente-res"
  
  /consultaServiciosContratados:
    post:
      tags:
      - "ESB Fuse"
      description: "Realiza la consulta de los datos del cliente"
      parameters:
      - in: "body"
        name: "/consultaServiciosContratados"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/consultaDatosCliente-in"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "/consultaServiciosContratados"
  /consultaProductosContratados:
    post:
      tags:
      - "ESB Fuse"
      summary: "/MessagingCentral"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "/MessagingCentral"
      parameters:
      - in: "body"
        name: "/MessagingCentral"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/consultaDatosCliente-in"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "/MessagingCentral"
  /validaotp:
    post:
      tags:
      - "ESB Fuse"
      description: "Servicio que realiza la validación del OTP"
      operationId: "validaOtp"
      parameters:
      - in: "body"
        name: "validaOTP"
        description: "Se requiere la validación de VACMAN del usuario y su OTP"
        required: true
        schema:
          $ref: "#/definitions/validaOTP"
      responses:
        200:
          description: "Tipos de datos de la respuesta del servicio"
          schema:
            $ref: "#/definitions/inline_response_403_1"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "OTP"

  /cambiapassword:
    post:
      tags:
      - "ESB Fuse"
      description: "Se requiere la validacion de la contraseña actual despues que\
        \ se compare la nueva contraseña si los dos pasos son exitoso se requiere\
        \ realizar una modificacion al atributo userPassword en LDAP para el numero\
        \ del cleinte (uid=$numCliente,ou=people,dc=multiva,dc=mx) previamente obtenido\
        \ en la entradas y se coloca el nuevo password proporcionado."
      operationId: "cambioPwdd"
      parameters:
      - in: "body"
        name: "cambioPwd"
        description: "Se requiere la validacion de la contraseña actual  "
        required: true
        schema:
          $ref: "#/definitions/cambioPwd"
      responses:
        200:
          description: "Estructura de la respuesta del servicio"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        
      x-swagger-router-controller: "Contrasea"
    x-swagger-router-controller: "cambioPwd"
  /ConsultaDatosCliente:
    post:
      tags:
      - "Middleware"
      summary: "/ConsultaDatosCliente"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "ConsultaDatosCliente"
      parameters:
      - in: "body"
        name: "ConsultaDatosCliente"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/consultaDatosCliente-in"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "ConsultaDatosCliente"
  /primerAcceso:
    post:
      tags:
      - "Middleware"
      summary: "/primerAcceso"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "primerAcceso"
      parameters:
      - name: id
        in: "header"
        description: 'El id es el identificador  del layout que el servicio va validar'
        required: false
        type: integer

      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200_4"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"
#-------------------------------------------------------------------      
  /MessagingCentralService:
    post:
      tags:
      - "Middleware"
      summary: "/MessagingCentralService"
      description: "Realiza el envio de email"
      operationId: "MessagingCentralServicePOST"
      parameters:
      - in: "body"
        name: "MessagingCentralService"
        description: "Realiza el envio de email"
        required: true
        schema:
          $ref: "#/definitions/sendEmail-in"
      responses:
        200:
          description: "Realiza el envio de email"
          schema:
            $ref: "#/definitions/sendEmail-res" 
      x-swagger-router-controller: "MessagingCentralService"
#------------------------------------------------------------------- 
  /ServiciosContratados:
    post:
      tags:
      - "Middleware"
      summary: "CentralService"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "CentralService"
      parameters:
      - in: "body"
        name: "CentralService"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/consultaDatosCliente-in"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "CentralService"
  /ProductosContratados:
    post:
      tags:
      - "Middleware"
      summary: "/MessagingService"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "/MessagingService"
      parameters:
      - in: "body"
        name: "/MessagingService"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/consultaDatosCliente-in"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "/MessagingService"

  /Validaotp:
    post:
      tags:
      - "Middleware"
      description: "Servicio que realiza la validación del OTP"
      operationId: "validaOTP"
      parameters:
      - in: "body"
        name: "validaOTP"
        description: "Se requiere la validación de VACMAN del usuario y su OTP"
        required: true
        schema:
          $ref: "#/definitions/validaOTP"
      responses:
        200:
          description: "Tipos de datos de la respuesta del servicio"
          schema:
            $ref: "#/definitions/inline_response_403_1"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "OTP"
    x-swagger-router-controller: "validaOTP"
  /Cambiapassword:
    post:
      tags:
      - "Middleware"
      description: "Se requiere la validacion de la contraseña actual despues que\
        \ se compare la nueva contraseña si los dos pasos son exitoso se requiere\
        \ realizar una modificacion al atributo userPassword en LDAP para el numero\
        \ del cleinte (uid=$numCliente,ou=people,dc=multiva,dc=mx) previamente obtenido\
        \ en la entradas y se coloca el nuevo password proporcionado."
      operationId: "cambioPwd"
      parameters:
      - in: "body"
        name: "cambioPwd"
        description: "Se requiere la validacion de la contraseña actual  "
        required: true
        schema:
          $ref: "#/definitions/cambioPwd"
      responses:
        200:
          description: "Estructura de la respuesta del servicio"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        
      x-swagger-router-controller: "Contrasea"
    x-swagger-router-controller: "cambioPwd"
  /Validacontrato:
    post:
      tags:
      - "Middleware"
      description: "Este servicio es para  cambiar la bandera de que el usuario acepto el contrato"
      operationId: "contrato"
      parameters:
      - in: "body"
        name: "contrato"
        description: "Se requiere la validacion de la contraseña actual"
        required: true
        schema:
          $ref: "#/definitions/contrato"
      responses:
        200:
          description: "Tipos de datos de respuesta"
          schema:
            $ref: "#/definitions/inline_response_200_4"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Contrato"
    x-swagger-router-controller: "contrato"
 

  /validacontrato:
    post:
      tags:
      - "Seguridad Nologin"
      description: "Este servicio es para  cambiar la bandera de que el usuario acepto el contrato"
      operationId: "contratoo"
      parameters:
      - in: "body"
        name: "contrato"
        description: "Se requiere la validacion de la contraseña actual"
        required: true
        schema:
          $ref: "#/definitions/contrato"
      responses:
        200:
          description: "Tipos de datos de respuesta"
          schema:
            $ref: "#/definitions/inline_response_200_4"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Contrato"
    x-swagger-router-controller: "contrato"
definitions:
  consultaDatosCliente-in:
    properties:
      idPersona:
        type: number
        example: "1025478963"
      ticket:
        type: "string"
        minLength: 1
        maxLength: 16
        example: "CUBA1234575SDF"
      canal:
        type: "string"
        minLength: 1
        maxLength: 5
        example: "CUBA1234575SDF"
  
  consultaDatosCliente-res:
    properties:
      numCliente:
        type: "integer"
        format: "int64"
        example: "Long"
      Nombre:
        type: "string"
        example: "String"
      listaDirecciones:
         type: "array"
         items:
          $ref: "#/definitions/listaDeDirecciones"
      rfc:
        type: "string"
        example: "String"
      listaTelefonos:
        type: "array"
        items:
          $ref: "#/definitions/listaDeTelefonos"
      listaEmails:
        type: "array"
        items:
          $ref: "#/definitions/listaDeEmail"
      tipoPersona:
        type: "string"
        example: "String"
      estatus:
        type: "string"
        example: "String"
      vip:
        type: "string"
        example: "String"
      responseStatus:
        type: "string"
        example: "String"
      responseError:
        type: "string"
        example: "String"
      
       
          
  listaDeEmail:
    properties:
      mail:
        type: "string"
        example: "String"
      activo:
        type: boolean
        example: "Boolean"
      tipoEmail:
        type: "string"
        example: "String"
     
        
  listaDeTelefonos:
    properties:
      telefono:
        type: integer
        example: "Integer"
      tipoTelefono:
        type: "string"
        example: "String"
    
        
        
  listaDeDirecciones:
    properties:
      direccion:
        type: "string"
        example: "String"
      poblacion:
        type: "string"
        example: "String"
      ciudad:
        type: "string"
        example: "String"
      estado:
        type: "string"
        example: "String"
      cp:
        type: "string"
        example: "String"
      tipoDireccion:
        type: "string"
        example: "String"
     
  inline_response_200:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"
      DescripcionResp:
        type: "string"
        example: "string"
      NumCliente:
        type: "string"
        example: "string"
      Nombre:
        type: "string"
        example: "string"
      Direccion:
        type: "string"
        example: "string"
      Poblacion:
        type: "string"
        example: "string"
      Ciudad:
        type: "string"
        example: "string"
      Estado:
        type: "string"
        example: "string"
      CP:
        type: "string"
        example: "string"
      RFC:
        type: "string"
        example: "string"
      Telefono1:
        type: "string"
        example: "string"
      Telefono2:
        type: "string"
        example: "string"
      Celular:
        type: "string"
        example: "string"
      Mail:
        type: "string"
        example: "string"
      TipoPersona:
        type: "string"
        example: "string"
      Estatus:
        type: "string"
        example: "string"
      Sucursal:
        type: "string"
        example: "string"
      ESVIP:
        type: "string"
        example: "string"
 
  inline_response_403_1:
     properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"
      DescRespuesta:
        type: "string"
        example: "string"
      Antiphishing:
        type: "integer"
        example: "integer"
  validaOTP:
    properties:
      Usuario:
        type: "string"
        example: "123456789"
      OTP:
        type: "string"
        example: "12345tftg56577654"
      Tipo:
        type: "integer"
        example: 1
  inline_response_200_2:
    properties:
      codigoError:
        type: "integer"
        example: "integer"
      mensajeError:
        type: "string"
        example: "string"

  cambioPwd:
    properties:
      Usuario:
        type: "string"
        example: "123456789"
      Contraseña_original:
        type: "string"
        example: "12345tftg5657765412wq"
      Nueva_contraseña:
        type: "string"
        example: "12345tftg5657765412wq"
      Comprueba_contraseña:
        type: "string"
        example: "12345tftg5657765412wq"
  inline_response_200_3:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"
     
 
  contrato:
    properties:
      Usuario:
        type: "string"
        example: "4333534"
      ContratoAceptado:
        type: "integer"
        example: 1
  
  inline_response_200_4:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"

        
#------------------------------------------------------------------------------------------
  sendEmail-in:
    properties:
      constante:
        type: "integer"
        example: 2
      idMensaje:
        type: "integer"
        example: 316
      correo:
        type: "string"
        example: "string"
      nombreUsu:
        type: "string"
        example: "string"       
      fechaHora:
        type: "string"
        example: "string" 



  sendEmail-res:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: 0

#----------------------------------------------------------------------------------------- 
  
